[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "extractor"
version = "0.0.1"

[project.scripts]
extractor = "extractor.__main__:main"

